In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Create a DataFrame from the provided data

# First, let's define the data as a list of lists (each inner list represents a row in the DataFrame)
data = [
    [1, 0.99, 90.01],
    [2, 1.02, 89.05],
    [3, 1.15, 91.43],
    [4, 1.29, 93.74],
    [5, 1.46, 96.73],
    [6, 1.36, 94.45],
    [7, 0.87, 87.59],
    [8, 1.23, 91.77],
    [9, 1.55, 99.42],
    [10, 1.4, 93.65],
    [11, 1.19, 93.54],
    [12, 1.15, 92.52],
    [13, 0.98, 90.56],
    [14, 1.01, 89.54],
    [15, 1.11, 89.85],
    [16, 1.2, 90.39],
    [17, 1.26, 93.25],
    [18, 1.32, 93.41],
    [19, 1.43, 94.98],
    [20, 0.95, 87.33]
]

# Define the column names
columns = ['Observation Number', 'Hydrocarbon Level x(%)', 'Purity y(%)']

# Create the DataFrame
df = pd.DataFrame(data, columns=columns)

df

    Observation Number  Hydrocarbon Level x(%)  Purity y(%)
0                    1                    0.99        90.01
1                    2                    1.02        89.05
2                    3                    1.15        91.43
3                    4                    1.29        93.74
4                    5                    1.46        96.73
5                    6                    1.36        94.45
6                    7                    0.87        87.59
7                    8                    1.23        91.77
8                    9                    1.55        99.42
9                   10                    1.40        93.65
10                  11                    1.19        93.54
11                  12                    1.15        92.52
12                  13                    0.98        90.56
13                  14                    1.01        89.54
14                  15                    1.11        89.85
15                  16                    1.20        90.39
16                  17                    1.26        93.25
17                  18                    1.32        93.41
18                  19                    1.43        94.98
19                  20                    0.95        87.33

In [14]:
from scipy import stats
import numpy as np

# Extracting the 'Hydrocarbon Level x(%)' and 'Purity y(%)' columns for linear regression analysis
x = df['Hydrocarbon Level x(%)']
y = df['Purity y(%)']

# Perform linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

# Conduct a t-Test to test the significance of the slope parameter
# Null hypothesis: slope = 0 (no relationship between hydrocarbon level and purity)
# Alternative hypothesis: slope != 0 (there is a relationship)

# The p-value obtained from the regression can be used to decide whether to reject the null hypothesis
# Typically, a p-value less than 0.05 is considered statistically significant

# Output the results
slope, intercept, r_value, p_value, std_err
p_val_from_t = 2 * stats.t.sf(np.abs(slope/std_err),len(x)-2)

print(p_val_from_t )#== p_value)
print(p_value)

# Calculate the two-tailed p-value using the t-distribution and the computed t-value
# Degrees of freedom is n - 2 (where n is the number of observations)

1.227314344459413e-09
1.2273143444594087e-09

In [7]:
degrees_of_freedom = len(x) - 2

# Calculate the two-tailed p-value
# We use the t.sf (survival function, which is 1-CDF) and multiply by 2 for the two-tailed test
p_value_from_t = 2 * stats.t.sf(np.abs(t0), degrees_of_freedom)

# Output the p-value calculated from the t-distribution and t0
p_value_from_t

1.227314344459413e-09

In [18]:
std_err**2

1.73385234102439